language: php

php:
  - 7.2

sudo: false

env:
  global:
    - PHPCS=0
    - PHPSTAN=0
    - RUN_TESTS=1

matrix:
  include:
    - php: 7.2
      env: PHPCS=1 RUN_TESTS=0
    - php: 7.2
      env: PHPCS=0 RUN_TESTS=0 PHPSTAN=1

before_script:
  - sleep 7 # Work around elasticsearch startup time.
  - phpenv rehash

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - if [[ $RUN_TESTS = 1 ]]; then composer test; fi
  - if [[ $PHPCS = 1 ]]; then composer cs-check; fi
  - if [[ $PHPSTAN = 1 ]]; then composer phpstan; fi

after_success:
  - if [[ $RUN_TESTS = 1 && $TRAVIS_PHP_VERSION = '7.2' ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
